# Generated by Django 2.0.1 on 2018-01-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180114_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='main_text',
        ),
    ]
