# Generated by Django 2.0.1 on 2018-01-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180114_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chest', '가슴'), ('back', '등'), ('shoulder', '어깨'), ('arm', '팔'), ('leg', '다리'), ('abdomen', '복부'), ('complex', '복합')], max_length=8)),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.RemoveField(
            model_name='weightworkout',
            name='muscle',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='weightworkout',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.CategoryWorkOut'),
            preserve_default=False,
        ),
    ]
