# Generated by Django 2.0.1 on 2018-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180122_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
