# Generated by Django 2.0.1 on 2018-01-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_question_is_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_secret',
        ),
        migrations.RemoveField(
            model_name='question',
            name='password',
        ),
    ]
